### ISSUE TITLE
Issue with image alignment

### ISSUE THREAD

**Issue by quintessence** [tenoku/boo#10]
I've been playing around with your theme and it's overall really nice, just having a couple of problems:

* When I insert an image I can't seem to override the default alignment (center), and there are times that I want to insert in-line images. This includes when I insert an image into a header line. I've tried using `style="!important` in HTML image tags, rather than Markdown, to no avail.
* I cannot seem to override the favicon, even though as far as I can tell I'm putting the favicon set I made in the correct directory and even have one just named `favicon.ico`...?

**Comment by eibt** [comment]
Hi @quintessence, thank you for your interest in this theme and I'm sorry for the late reply, here are some things you can try:

1. To avoid using `!important` simply use a more specific CSS selector, like this:
```
<style type="text/css">
  .content .post .post-content img {
    display: inline;
    padding: 0;
    left: 0;
    -webkit-transform: none;
    transform: none;
  }
</style>
```
You can try adding the above code to your post's code injection section:
![codeinjection](https://user-images.githubusercontent.com/5503784/32925404-6c8e0094-cb07-11e7-8779-79c76653d090.gif)

That will produce the following result:

**Before:**
---
![captura de pantalla 2017-11-16 a las 7 53 02 p m](https://user-images.githubusercontent.com/5503784/32925558-1cc1eaa2-cb08-11e7-9710-a48ea24bb561.png)

**After:**
---
![captura de pantalla 2017-11-16 a las 7 52 33 p m](https://user-images.githubusercontent.com/5503784/32925564-25696824-cb08-11e7-80c6-a2b408444a87.png)

This will work with markup, and you can also add inline images to headings:

**Before:**
---
![captura de pantalla 2017-11-16 a las 7 58 51 p m](https://user-images.githubusercontent.com/5503784/32925661-b35c432c-cb08-11e7-8f61-1710c725d760.png)

**After:**
---
![captura de pantalla 2017-11-16 a las 7 59 06 p m](https://user-images.githubusercontent.com/5503784/32925691-de605388-cb08-11e7-9fe5-728ab3616a45.png)

2. To update your favicon in Ghost 1.0 and later you can simply go to your admin panel >Settings > General, and you'll see the option to do this in the "Publication identity" section:

![captura de pantalla 2017-11-16 a las 8 03 26 p m](https://user-images.githubusercontent.com/5503784/32925804-7d50ccac-cb09-11e7-86e9-b6ea0734447b.png)

In previous versions of Ghost each theme could override the favicon but now the only option seems to be uploading it using this interface.

Please let me know if it helped, cheers!

**Comment by quintessence** [comment]
Ah I didn't realize they moved the favicon to be in the UI only. That explains so much. Thank you! Also, the CSS code injection worked :) Again, greatly appreciate :)

**Comment by eibt** [comment]
Awesome! You're welcome!
