### ISSUE TITLE
Image are not appearing on large display

### ISSUE THREAD

**Issue by pascalandy** [tenoku/boo#2]
Hi,

Any idea why the header picture is not displaying correctly on large display ?
See this screencast: https://cl.ly/1K3X3U1C0k1e

I run Ghost 0.11.7

Thank you!

**Comment by eibt** [comment]
Hi @pascalandy Thank you very much for pointing this out. I'm trying to replicate this issue using the latest version of Chrome and Ghost 0.11.7, however I'm not being able to replicate it with this setup.

Could you tell me which version of Chrome you are using, also please check you have extra code in the code injection section of your admin area, if so, try to remove it temporarily and check if the problem still shows up.

Also let me know if you can see the same issue in the demo at https://boo-demo.tenoku.com/

thank you!

**Comment by pascalandy** [comment]
Well well... On https://boo-demo.tenoku.com/ everything looks perfect.

I deleted code in the code injection section and everything works normally now. So clearly and issue on my setup! 

Thanks for caring ;)

**Comment by eibt** [comment]
You're welcome!
