### ISSUE TITLE
Do you follow Casper parent themes updates?

### ISSUE THREAD

**Issue by pascalandy** [tenoku/boo#3]
I have another question for you :_)

Do you follow Casper parent themes updates? If so which version is your theme based on? Casper is now at 1.3.6

Cheers!

**Comment by eibt** [comment]
Good question, Yes! I keep track of the Casper theme repo and apply the relevant commits to this project, so far everything is up to date with Casper version 1.3.6 , the original fork was made on Casper version 1.3.3 :)

**Comment by pascalandy** [comment]
Thank you very much for clarifying this :)

**Comment by eibt** [comment]
You're welcome! 😃
