### ISSUE TITLE
Uploading Top-Left Logo Image

### ISSUE THREAD

**Issue by wanzihua** [tenoku/boo#5]
Hi guys,

I'm having trouble locating in the file structure where to reference to the logo that should appear on the top left of the blog. I see where to reference a logo image for the favicon but not the top left icon as the demo. Also is there a recommended size? 

Or has this been dropped in favor of uploading a logo in the admin panel? Thx.

**Comment by eibt** [comment]
@wanzihua that is correct, you can do this from the admin panel, try following these steps:

1. Log into your blog: **yourblog.ghost.io/ghost**
2. Click **General** under the settings section
3. You'll find the option to upload or change your logo below the **Blog Logo** label

For a reference [this is the image](https://boo-demo.tenoku.com/content/images/2017/01/boo-theme-logo.png) used in the demo. The img element containing the logo is set to a height of ***38px*** and a width of ***auto*** to keep the proportion of the image.

Let me know if this solves the problem 👍

**Comment by wanzihua** [comment]
Thank you @eibt. Also, can you tell me the font name is for the theme. Especially the font of your "Boo" text in the logo?

**Comment by eibt** [comment]
Hi @wanzihua! This theme uses Open Sans (https://fonts.google.com/specimen/Open+Sans) and Lato (https://fonts.google.com/specimen/Lato), the font in the logo is Open Sans Semibold :)

**Comment by eibt** [comment]
@wanzihua It's been a while since this question is open so it's a good time to close it , If you have any other questions please open a new issue and I'll be happy to answer 👍
