### ISSUE TITLE
Can't get google analytics to work

### ISSUE THREAD

**Issue by ahale9464** [tenoku/boo#7]
I am using my google analytics code in the header, and for some reason it's not working. Plz help.

**Comment by eibt** [comment]
Hi @ahale9464! Sure! so first let's verify that you're getting the correct tracking code, please check 
 [these instructions](https://support.google.com/analytics/answer/1008080?hl=en#trackingID) and copy the **tracking code snippet**, note that you must include the `<script>` and `</script>` tags.

So the code you copy should look like this:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'YOUR_TRACKING_ID', 'auto');
  ga('send', 'pageview');

</script>
```

Once you get that code, go to the admin panel in your blog (e.g. **yourblog.ghost.io/ghost**) and click **Code injection** on the left menu, then paste the code in the **Blog Header** text area and click **Save**.

Let me know if this solves the issue!

**Comment by ahale9464** [comment]
Thanks for the response! My code looks very similar to yours. Yet when I go to my analytics page is shows 0s across the board. Not sure what I'm missing.

**Comment by eibt** [comment]
@ahale9464 ok! check this and let me know if it solves it 👍 

[Analytics troubleshooter](https://support.google.com/analytics/troubleshooter/7400465)

**Comment by gvagenas** [comment]
Hi @ahale9464 , I had exactly the same issue as you and the problem was the `uBlock` ad blocking extension. 
Very helpful to debug was Google Tag Assistant the https://support.google.com/tagassistant/answer/2947093?hl=en

George
