### ISSUE TITLE
Let me know if I can help :-p

### ISSUE THREAD

**Issue by pascalandy** [tenoku/boo#8]
Hi,

I just tried your theme over Ghost 1.5.2 and I love it. I’m the owner of [play-with-ghost](http://play-with-ghost.com/) and one big feature I'm working on is to showcase templates like your that I enjoy. 

Let me know if I can help you by hosting a staging environment of your Ghost project(s) or anything related of the backend of hosting Ghost.

Cheers!
[Pascal](https://twitter.com/askpascalandy/)

**Comment by eibt** [comment]
Hi Pascal! sorry for the delayed reply, I tested [play-with-ghost.com](http://play-with-ghost.com/), very neat and useful for quickly experimenting with themes and content, I look forward to seeing the themes showcase and see what's coming next. Keep up the great work! 👍

**Comment by pascalandy** [comment]
Thanks Ivan!
I'm redesigning the site at the moment and I'll be happy to get not-easy-to-hear-feedback from you. I'll let you know :)
