### ISSUE TITLE
Header images are breaking since I updated to Ghost 1.15.1

### ISSUE THREAD

**Issue by pascalandy** [tenoku/boo#9]
Just to let you know.

Here is the GIF - https://jumpshare.com/v/oJV7MW9eP4e1uekPL6ev

Also, the behavior of my other themes is still normal.
Thanks!

**Comment by eibt** [comment]
Hi Pascal, thank you so much for letting me know, I'll check this asap

**Comment by pascalandy** [comment]
I remember have opened this https://github.com/tenoku/boo/issues/2

I removed everything from the Code Injection section, clear my cache and it's the same result.

Thanks!

**Comment by eibt** [comment]
Awesome! just to confirm, this solved the issue correct?

**Comment by pascalandy** [comment]
No,
The header images disappear when the resolution is higher than about 1280px.

**Comment by eibt** [comment]
Thank you, I'm testing on a clean installation of Ghost 1.15.1 but I'm being unable to reproduce the issue, could you please check the following?

- Check that you're using the [latest theme release](https://github.com/tenoku/boo/releases/tag/v1.0)
- Make sure you don't have any CSS or JavaScript in the [post code injection](https://blog.ghost.org/post-code-injection/)
![codeinjection](https://user-images.githubusercontent.com/5503784/32011378-d4f9a220-b971-11e7-8f07-e76611a93edd.gif)
- Check that you're using the latest version of Google Chrome
- Try temporarily disabling any Chrome extensions and check if the problem persists
- Make sure you don't have any conflicting JavaScript code or CSS in your posts' content
- Try opening the blog in an incognito window to discard any caching issues

Please let me know if the problem persists after going through the checklist above. Cheers!

**Comment by pascalandy** [comment]
I don't understand why it happened. Today it's all good.
Thank you for your dedication!

**Comment by eibt** [comment]
You're very welcome! I'm glad you solve the issue!

Cheers!
